POST http://localhost:3030/api/users/register HTTP/1.1
Content-Type: application/json

{
    "email" : "comocomo@gmail.com",
    "username" : "Anakz",
    "password": "12345",
    "bio": "www.bio.com"
}

###

POST http://localhost:3030/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email" : "anasakzaz23@gmail.com",
    "password": "azerty"
}

###

Put  http://localhost:3030/api/users/me HTTP/1.1
Content-Type: application/json

{
    "Authorization" : "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MzIzMDU5NzksImV4cCI6MTYzMjMwOTU3OX0.Q5JLnMTrNUlzrks6RBIKVNsTTqKlc6jHqRPKZymYo04",
    "bio": "nouvelle bio"
}